default:
  image: "jlk.fjfi.cvut.cz:5000/fjfi-mmg/archlinux-tnl-cuda:latest"
  before_script:
    # make sure that $PATH and other essential variables are set correctly
    - source /etc/profile
    # 1. fall back to arch 7.0 when the builder has no GPU to avoid building for all GPU architectures
    # 2. cmake can't detect the native architecture when using clang
    - if ! nvidia-smi --list-gpus > /dev/null; then
            CUDA_ARCH=70;
      elif [[ ${CUDACXX} == "clang++" ]]; then
            CUDA_ARCH=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | head -n 1 | tr -d '.');
      else
            CUDA_ARCH=native;
      fi

# automatically initialize git submodules
# https://docs.gitlab.com/ee/ci/git_submodules.html
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build_Release:
  stage: build
  script:
    - cmake -B build -S . -G Ninja
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_CUDA_ARCHITECTURES=${CUDA_ARCH}
    - ninja -C build

build_Debug:
  stage: build
  script:
    - cmake -B build -S . -G Ninja
            -DCMAKE_BUILD_TYPE=Debug
            -DCMAKE_CUDA_ARCHITECTURES=${CUDA_ARCH}
    - ninja -C build
